name: PR Fork Check â€“ Multi Jobs Test

on:
  pull_request:

jobs:
  job-a:
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸš€ Job A exÃ©cutÃ© (PR interne)"

  job-b:
    name: Job B (depends on job-a)
    needs: job-a
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸš€ Job B exÃ©cutÃ© (PR interne)"

  job-c:
    name: Job C (depends on job-a)
    needs: job-a
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ§ª Job C exÃ©cutÃ© (PR interne)"